parameters:
#    tn_group.example.class: Videl\TNGroupBundle\Example

services:
#    tn_group.example:
#        class: %tn_group.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
