<?php

namespace Videl\TNGroupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRightsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRightsRepository extends EntityRepository
{
}
